spring:
  application:
    name: zuul

server:
  port: 8080

zuul:
  routes:
      user:
        path: /user/**
        serviceId: user
      movie:
        path: /movie/**
        serviceId: movie
      theater:
        path: /theater/**
        serviceId: theater
      order:
        path: /order/**
        serviceId: order

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


---
spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/